language: ruby

rvm:
  - 2.7
  - 3.0

sudo: false

bundler_args: --without production

before_install:
  - gem install bundler -v 2.2.9 # https://docs.travis-ci.com/user/languages/ruby/#bundler-20

script:
  - JENKINS=true bundle exec rspec --profile
